###GET all customer Info
GET http://localhost:8080/customers

###Get a specific customer by id - unavailable id input
GET http://localhost:8080/customers/1

###Get a specific customer by id 
GET http://localhost:8080/customers/5

###Get a specific customer by id - invalid id input
GET http://localhost:8080/customers/

###Get a specific customer by id - invalid id input
GET http://localhost:8080/customers/er

###Get a specific customer by id - invalid id input
GET http://localhost:8080/customers/7.0


###Add One Customer
POST  http://localhost:8080/customers 
Content-Type:  application/json 

{
    "firstName": "name111",
    "lastName": "name111",
    "email": "name111@here111.com",
    "investmentPreferences":  {
      "investmentAmount": 1000.00,
      "duration": "ONE_YEAR",
      "riskTolerance": "LOW",
      "investmentGoal":"EDUCATION",
      "chosenStockSymbol": "AAA"
    } ,
    "createdDate": "2023-11-03T04:21:42.26759",
    "updatedDate": "2023-11-03T04:21:42.267609"
  }


###Add Another Customer
POST  http://localhost:8080/customers
Content-Type:  application/json 

{
    "firstName": "name222",
    "lastName": "name222",
    "email": "name222@here222.com",
    "investmentPreferences":  {
      "investmentAmount": 2000,
      "duration": "FIVE_YEARS",
      "riskTolerance": "HIGH",
      "investmentGoal":"RETIREMENT",
      "chosenStockSymbol": "BBB"
    } ,
    "createdDate": "2023-11-03T04:21:42.26759",
    "updatedDate": "2023-11-03T04:21:42.267609"
  }


###Add Another Customer
POST  http://localhost:8080/customers
Content-Type:  application/json 

{
    "firstName": "name333",
    "lastName": "name333",
    "email": "name233@here333.com",
    "investmentPreferences":  {
      "investmentAmount": 33000,
      "duration": "TEN_YEARS",
      "riskTolerance": "HIGH",
      "investmentGoal":"EDUCATION",
      "chosenStockSymbol": "CCC"
    } ,
    "createdDate": "2023-11-03T04:21:42.26759",
    "updatedDate": "2023-11-03T04:21:42.267609"
  }


###UPDATE Customer Info 
PUT http://localhost:8080/customers/1
Content-Type: application/json

{
    "firstName": "name11updated",
    "lastName": "name111",
    "email": "name111@hereup111.com",
    "investmentPreferences":  {
      "investmentAmount": 1011,
      "duration": "FIVE_YEARS",
      "riskTolerance": "LOW",
      "investmentGoal":"RETIREMENT",
      "chosenStockSymbol": "AAA"
    } ,
    "createdDate": "2023-11-03T04:21:42.26759",
    "updatedDate": "2023-11-03T04:21:42.267609"
  }

###Update Customer Info - will throw error
PUT http://localhost:8080/customers/5
Content-Type: application/json

{
    "firstName": "name555",
    "lastName": "name555",
    "email": "name555@here555.com",
    "investmentPreferences":  {
      "investmentAmount": 5500.00,
      "duration": "ONE_YEAR",
      "riskTolerance": "LOW",
      "investmentGoal":"EDUCATION",
      "chosenStockSymbol": "DDD"
    } ,
    "createdDate": "2023-11-03T04:21:42.26759",
    "updatedDate": "2023-11-03T04:21:42.267609"
  }


###Delete Customer from Database - sucessfully
DELETE http://localhost:8080/customers/1

###Delete Customer from Database - unsucessfully
DELETE http://localhost:8080/customers/88k
Content-Type: application/json

###Delete Customer from Database - sucessfully
DELETE http://localhost:8080/customers/3
